[thehit]
title = "THE HIT"
url = "https://the-hit.co/"
entrySelector = "div[class^='ServiceItemList_wrapper'] ul li[class^='ServiceItemList_item']"
titleSelector = "h2[class^='euiTitle euiTitle']"
linkSelector = "a"
contentSelector = "p[class^='ServiceItem_ServiceItem__summary']"
waitForSelector = "div[class^='ServiceItemList_wrapper'] ul li[class^='ServiceItemList_item']"
onFail = "stale"

[disquiet]
title = "Disquiet ─ 전체"
url = "https://disquiet.io/?sort=recent&type=all"
entrySelector = "div[class*='clickable']"
titleSelector = "div.card-header div.card-title"
linkSelector = "*"
contentSelector = "div.sc-bOdqNl.jzLQXV"
waitUntil = "networkidle"

[disquiet_product]
title = "Disquiet ─ 프로덕트"
url = "https://disquiet.io/?sort=recent&type=product"
entrySelector = "div[class*='clickable']"
titleSelector = "div.card-title"
linkSelector = "*"
contentSelector = "div.sc-jEUCeg.fklEVh div.sc-bOdqNl.jzLQXV"
waitUntil = "networkidle"

[disquiet_makerlog]
title = "Disquiet ─ 메이커로그"
url = "https://disquiet.io/?sort=recent&type=maker_log"
entrySelector = "//html/body/div[3]/div[2]/div[2]/div[6]/div/div[2]/div/div/div[2]"
titleSelector = "div.title"
linkSelector = "*"
contentSelector = "div[class*='ql-editor']"
waitUntil = "networkidle"

[wwit]
title = "WWIT"
url = "https://wwit.design/"
entrySelector = "div.c-post-card"
titleSelector = "h2.c-post-card__title"
linkSelector = "h2 a.c-post-card__title-link"
contentSelector = "div.c-post-card__content > div > div:nth-child(2) > a"
imageSelector = "a.c-post-card__image-link img.c-post-card__image.js-fadein.is-inview"
waitUntil = "networkidle"

[geeknews_show]
title = "GeekNews Show"
url = "https://news.hada.io/show"
entrySelector = "td.topictitle"
titleSelector = "h1"
linkSelector = "a"
contentSelector = "span.topicurl"
waitUntil = "networkidle"
